dotnet add AutoLot.Models package Microsoft.EntityFrameworkCore.SqlServer -v [8.0.*,9.0)
dotnet add AutoLot.Models package System.Text.Json -v [8.0.*,9.0)
dotnet add AutoLot.Models package Microsoft.VisualStudio.Threading.Analyzers -v [17.*,)
dotnet add AutoLot.Dal package Microsoft.EntityFrameworkCore.SqlServer -v [8.0.*,9.0)
dotnet add AutoLot.Dal package Microsoft.EntityFrameworkCore.Design -v [8.0.*,9.0)
dotnet add AutoLot.Dal package Microsoft.VisualStudio.Threading.Analyzers -v [17.*,)
dotnet add AutoLot.Dal.Tests package Microsoft.EntityFrameworkCore.SqlServer -v [8.0.*,9.0)
dotnet add AutoLot.Dal.Tests package Microsoft.EntityFrameworkCore.Design -v [8.0.*,9.0)
dotnet add AutoLot.Dal.Tests package Microsoft.Extensions.Configuration.Json -v [8.0.*,9.0)
dotnet add AutoLot.Dal.Tests package Microsoft.NET.Test.Sdk  -v [17.*,)
dotnet add AutoLot.Dal.Tests package Microsoft.VisualStudio.Threading.Analyzers -v [17.*,)
dotnet add AutoLot.Dal.Tests package xunit -v [2.*,3.0)
dotnet add AutoLot.Dal.Tests package xunit.runner.visualstudio -v [2.*,3.0)
dotnet add AutoLot.Dal.Tests package coverlet.collector -v [6.0.*,7.0)
pause
